Payday/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('payday.urls', namespace="payday")),
    url(r'^auth/', include('register.urls', namespace="auth")),
    url(r'^admin/', admin.site.urls),
]

payday/urls.py
from django.conf.urls import url
from . import views

app_name = "payday"

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^new/$', views.NewEntryView.as_view(), name="new"),
    url(r'^count/$', views.CountView.as_view(), name="count"),
]

register/urls.py
from django.conf.urls import url
from . import views


app_name = "register"

urlpatterns = [
    url(r'^register/$', views.SignUp.as_view(), name="register"),
    url(r'^login/$', views.SignIn.as_view(), name="login"),
    url(r'^logout/$', views.Logout.as_view(), name="logout"),
]

payday/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from register.forms import User


# Create your models here.
class Entry(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    day = models.DateField("Дата")
    hours = models.PositiveIntegerField("Отработанные часы", validators=[MinValueValidator(0), MaxValueValidator(24)])
    work_description = models.CharField("Описание работы", max_length=200)
    create_date = models.TimeField("Дата создания записи")

    def __str__(self):
        return self.work_description

payday/forms.py
from django import forms
from .models import Entry


class EntryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        initial = kwargs.get('initial', {})
        initial["hours"] = 8
        kwargs['initial'] = initial
        super(EntryForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Entry
        fields = (
            "day",
            "hours",
            "work_description"
        )
        labels = {
            "day": "День",
            "hours": "Отработанное время",
            "work_description": "Описание работы",
        }
        initials = {
            "hours": 8,
        }


class CountForm(forms.Form):
    from_date = forms.DateField()
    to_date = forms.DateField()
    hour_rate = forms.FloatField(label="Зарплата за час (в долларах):", min_value=0.0, initial=5)
    company_rate = forms.FloatField(label="Сколько забирает фирма (в процентах):", min_value=0.0, initial=37)
    manager_rate = forms.FloatField(label="Сколько забирает менеджер (в процентах):", min_value=0.0, initial=8)
    exchange_rates = forms.FloatField(label="Курс гривны:", min_value=0.0, initial=25)

    def clean_to_date(self):
        from_date = self.cleaned_data.get("from_date")
        to_date = self.cleaned_data.get("to_date")

        if from_date > to_date:
            raise forms.ValidationError("Первая дата должна быть меньше второй")

        if not Entry.objects.filter(day__gte=from_date).filter(day__lte=to_date).exists():
            raise forms.ValidationError("Вы не работали в эти дни")

        return to_date

payday/views.py
from datetime import datetime
from django.views.generic import ListView, CreateView, FormView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy

from .models import Entry
from .forms import EntryForm, CountForm


class IndexView(ListView):
    http_method_names = ["get"]
    queryset = Entry.objects.order_by("-create_date")[:30]
    template_name = "payday/index.html"
    context_object_name = "last_third_entries"


class NewEntryView(CreateView):
    http_method_names = ["get", "post"]
    template_name = "payday/new.html"
    form_class = EntryForm
    success_url = "/"

    @method_decorator(login_required(login_url=reverse_lazy("register:login")))
    def dispatch(self, request, *args, **kwargs):
        return super(NewEntryView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        entry = form.save(commit=False)
        entry.create_date = datetime.now()
        entry.user = self.request.user
        entry.save()
        return super(NewEntryView, self).form_valid(form)


class CountView(FormView):
    http_method_names = ["get", "post"]
    template_name = "payday/count.html"
    form_class = CountForm
    success_url = "/count"
    context_object_name = "result"

    @method_decorator(login_required(login_url=reverse_lazy("register:login")))
    def dispatch(self, request, *args, **kwargs):
        return super(CountView, self).dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = request.POST
        date_interval = Entry.objects.filter(day__gte=form["from_date"])\
                                     .filter(day__lte=form["to_date"])\
                                     .filter(user_id=request.user.id)
        total_hours = 0
        for hours in date_interval:
            total_hours += hours.hours

        hour_rate = float(form["hour_rate"])
        exchange_rates = float(form["exchange_rates"])
        manager_rate = float(form["manager_rate"])
        company_rate = float(form["company_rate"])

        total_result = get_results(total_hours, hour_rate, exchange_rates, manager_rate, company_rate)
        content = super(CountView, self).get_context_data(**kwargs)
        content.update(total_result)

        return self.render_to_response(content, **kwargs)


def get_results(total_hours, hour_rate, exchange_rates, manager_rate, company_rate):
    total_money_in_usd = total_hours * hour_rate
    total_money_in_uan = total_money_in_usd * exchange_rates
    manager_result_in_usd = total_money_in_usd * (manager_rate / 100)
    company_result_in_usd = total_money_in_usd * (company_rate / 100)
    user_result_in_usd = total_money_in_usd - manager_result_in_usd - company_result_in_usd
    manager_result_in_uan = manager_result_in_usd * exchange_rates
    company_result_in_uan = company_result_in_usd * exchange_rates
    user_result_in_uan = user_result_in_usd * exchange_rates

    total_result = {
        "total_money_in_usd": total_money_in_usd,
        "total_money_in_uan": total_money_in_uan,
        "manager_result_in_usd": manager_result_in_usd,
        "manager_result_in_uan": manager_result_in_uan,
        "company_result_in_usd": company_result_in_usd,
        "company_result_in_uan": company_result_in_uan,
        "user_result_in_usd": user_result_in_usd,
        "user_result_in_uan": user_result_in_uan,
    }

    for key, result in total_result.items():
        if total_result[key].is_integer():
            total_result[key] = int(total_result[key])
        else:
            total_result[key] = float("{0:.2f}".format(result))

    return total_result

payday/templates/payday/count.html
{% extends "payday/parent.html" %}
{% load widget_tweaks %}

{% block content %}
    {% include "payday/forms/count_form.html" %}
    {% if total_money_in_usd %}
        <div class="show col-xs-12 col-md-6 col-md-offset-3">
            <p>За период с {{ from_date }} до {{ to_date }}</p>
            <p>Всего заработано за этот период {{ total_money_in_usd }} долларов или же {{ total_money_in_uan }}
                гривен</p>
            <p>Фирма заработала {{ company_result_in_usd }} долларов или же {{ company_result_in_uan }}
                гривен</p>
            <p>Менеджер заработал {{ manager_result_in_usd }} долларов или же {{ manager_result_in_uan }}
                гривен</p>
            <p> Вы заработали {{ user_result_in_usd }} долларов или же {{ user_result_in_uan }} гривен</p>
        </div>
    {% endif %}

{% endblock %}

payday/templates/payday/index.html
{% extends "payday/parent.html" %}

{% block content %}

    {% if user.is_authenticated %}
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}"><h1>{{ message }}</h1></li>
                {% endfor %}
            </ul>
        {% endif %}

        <div class="container">
            <table class="table">
                <thead>
                <tr>
                    <th>Пользователь</th>
                    <th>Дата</th>
                    <th>Отработанное время</th>
                    <th>Описание работы</th>
                </tr>
                </thead>
                <tbody>
                <tr>

                </tr>

                {% for entry in last_third_entries %}
                    <tr>
                        <td>{{ entry.user|title }}</td>
                        <td>{{ entry.day }}</td>
                        <td>{{ entry.hours }}</td>
                        <td>{{ entry.work_description }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div>

        </div>
    {% endif %}
{% endblock %}

payday/templates/payday/new.html
{% extends "payday/parent.html" %}

{% block content %}
    {% include "payday/forms/new_entry_form.html" %}
{% endblock %}

payday/templates/payday/parent.html
<!doctype html>
<html lang="ru">
{% load staticfiles %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>PayDay</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker-standalone.css">
    <link rel="stylesheet" href="{% static "/style/style.css" %}">

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
</head>

<body>
<h1 id="name">PayDay</h1>


<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">PayDay</a>
        </div>
        <div class="navbar-collapse collapse" style="height: 1px;margin: auto;text-align: center;">
            <ul class="nav navbar-nav">
                <li {% if request.resolver_match.url_name == "index" %} class="active" {% endif %} ><a
                        href={% url 'payday:index' %}>Домашняя страница</a></li>
                <li {% if request.resolver_match.url_name == "new" %} class="active" {% endif %} ><a
                        href={% url 'payday:new' %}>Добавить запись</a></li>
                <li {% if request.resolver_match.url_name == "count" %} class="active" {% endif %} ><a
                        href={% url 'payday:count' %}>Расчитать зарплату</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if not user.is_authenticated %}
                    <li><a href={% url 'register:register' %}>Регистрация</a></li>
                    <li><a href={% url 'register:login' %}>Войти</a></li>
                {% else %}
                    <li><span class="navbar-text">Добро пожаловать, {{ user.username }}</span></li>
                    <li><a href={% url 'register:logout' %}>Выйти</a></li>
                {% endif %}
            </ul>
        </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
</div>

{% block content %}
{% endblock %}

</body>
</html>